#ENC[AES256_GCM,data:82wZ9VGAA8G0DsV+s510PuFOmREncsgwK6J4WF6gJUfASDltVwJhLrFJig==,iv:77b80Nu+jw298wAqvdwaUv7fOz3nTImNFHs8AhDA5xQ=,tag:7rSWSTRJYLV7W7eKMEmH4Q==,type:comment]
#ENC[AES256_GCM,data:qsFjIOvf1K/VjriEG7POHNtwK6cDrJ2dYycctamL08gqkZC2alvhGWUIB558vQ==,iv:CrMl9rrqo9FuJEx2Xk0eiFxZ0WMKSnpS0WJc7W4qTyY=,tag:78CrvpQpWrUl6FMfFfb8SQ==,type:comment]
#ENC[AES256_GCM,data:OJH9WdYC0jUEpJtribR0Nk3iYv0j/Hvhe/20AHEP+yRXpPtgN1YXWYNMuX8GX/x5if4q41fmrQpr6ic2ZvqP6Nz8tjKpJRFhAGxXC9iJgRWh1t4501jIyM0wmXhxM0P2CAMM8mpoFWU3,iv:qp9IYm44SoO9p+LVgHpP8dukqL3AZ9VQ2/2QXvf7+kI=,tag:iF8JejfktA32FS9qM03stA==,type:comment]
#
#ENC[AES256_GCM,data:UgaoinrfCE1j5rEJlxfDC2ld4uNrMTtVogy6AiVjstsGgGm+S97JTQ==,iv:rQzNMZRXp8YgNx0CyY6RbjyV/q2KFhnonJr6xfNXD4g=,tag:9SA5oHuBR50lT3pNM1SVIA==,type:comment]
#ENC[AES256_GCM,data:XVHqTDl8s1U/Mdl6GDoeZ/4J9XqIspLfOUb90NtZV7dsNYRjasjUXl9f134iIdLLkxW3Zarjcx2EK4pp,iv:/039zXLW/n6zLZSi6hSJ0Mh++qYRbH3KqvgdldkR+cs=,tag:tomP5MsgYdan1tA+wPgjNg==,type:comment]
#ENC[AES256_GCM,data:Kfc1XHW7h+lPvOAvn1VEYdceFg==,iv:w7faVB2RVJG3tbsivPZXYZscMQHgu+6306xm26h7pOA=,tag:4rDLqPlCaVCN+9Eqc/aYtg==,type:comment]
uuid: ENC[AES256_GCM,data:wlmYZEOmvF4vfCzN2tvKhkitY2h8FbQraSLy2X+pu0GblqUZ,iv:sy3XpE/2uQuyWmsIaQFmxzvR/OpF0u4xGhiTwLalBbU=,tag:zFlEM+R90yZQPbqNNNnDpg==,type:str]
admin_uuid: ENC[AES256_GCM,data:qsnJpBIeQ7t4b2Ih4AzvNMJEWc6wEYioT7A/dBgb7KB3ntMG,iv:+Kv7uBb1mhYkkZq0bVXxbCmzNNLAncxhpKZqha9jRdo=,tag:hvt0NOPQmXxG054YXq4NEw==,type:str]
salamander_password: ENC[AES256_GCM,data:tjiqcYOY8khh3EQA6H18aOc5Up1a1A==,iv:rzJEShcywrFhk2ytGAeVAE63FEBH18LOiRjvFxWHWkE=,tag:qkH53jUOkqXH0XWCaP8jXQ==,type:str]
shadowtls_password: ENC[AES256_GCM,data:+DAAhGm0b0REHuJXHAJm5i2TZD7SjA==,iv:6rkf60DySd29L4K65F+HBCxhYxPcN8yDY5FtCNsO1Ms=,tag:BgXZhZ5f45NPcS605T8VXg==,type:str]
#ENC[AES256_GCM,data:h72Up19fVkvNLBIZ0Sl+CTuaf8Mci4skX1JrlmwqF0d9k5bPbg==,iv:1F03pOKIN1GtkntNRGluFcIvzrFM98y0BhJ1rcf6k/M=,tag:/MCLIl8W9xVf3SQEAYvl8w==,type:comment]
ss2022:
    helsinki: ENC[AES256_GCM,data:4MnR17Y+MCc/rYehN3MKjRMJ1L0vBjpJ,iv:K/msxyLcFa0Gdjbl86YzcdJdhc/Z3cSip/6MrevAGZs=,tag:8UINydsj1FS9mXxgN5hb/g==,type:str]
    oracle: ENC[AES256_GCM,data:d4SE4ik1Wd1C66tXdWx+kvOSfB3Hi95t,iv:ZoiwSpQKMBsEXBqOeW8H3ED5O0jiv18v/gxIbv9/3Qk=,tag:qwpy9Rbs88aAY9k9xz3IyA==,type:str]
    gcp: ENC[AES256_GCM,data:zI5dyXu1CiKUvSk7z5/fwrC3dLZ31w1u,iv:mSGgPRdHp55y3lJKVRObABrGBbgOISP2pzArfZcQJQo=,tag:Zkr+Umw4MIJmcOpVLC1Q/w==,type:str]
    scaleway: ENC[AES256_GCM,data:ldzRLBzfripdkax4qUp63yGpjjsbuRag,iv:kr8oGIMrNP35gxXDAIOk3IZvG9MItae65dvhNRqagAk=,tag:q+rJzvtt81+kHoF7Se1TLw==,type:str]
    user_key: ENC[AES256_GCM,data:VQ6Ha7GoqY9LAB5OCZ28V9AM+9grEih7,iv:kNXNJBcRsi+9x9ZqqCVuBGvwV2UqTo9tJ53VLPQ83PU=,tag:cZqcdePlT48S0e2Ik2BWfg==,type:str]
#ENC[AES256_GCM,data:lTagnpWT/+HocCPR5VguPi8QpegAyPQi1XU5zaIxUaDQ6yJz/jK73WJtlo0=,iv:xpHIdtvmtEPR5J/jAv7lb+xEtltchjx/EYN+M4r1R38=,tag:jUKMOjCJTI2vvmmL6GZnUg==,type:comment]
servers:
    helsinki:
        ip: ENC[AES256_GCM,data:pOO1M0CTb1Y=,iv:ZFS6b0YRZaWUtHJsD42gFrwzOIeKVCNSaDgXqpDm64Q=,tag:A6myW+fN2fJe8mETXIHtcA==,type:str]
    oracle:
        ip: ENC[AES256_GCM,data:9JcerXdhEbU=,iv:+XTek0GSHEv4Mb/QS1QFflXSdU0Uv2M8T+vs2C4Iwwg=,tag:uU879s/ostyKJ5FF76syWg==,type:str]
    gcp:
        ip: ENC[AES256_GCM,data:Ph1zCVLn8Y8=,iv:VWQ5r4q1fiIVI1r81RmJdKgl8SH4hjBSRxYQA+N4n7U=,tag:zAKqvBVndxnLdnLVXivxwQ==,type:str]
    scaleway:
        ip: ENC[AES256_GCM,data:r6kzq1BywYw=,iv:Y8zs9oe5Nzo3qqQr8VFHXc/Gkaq8BtjcLouc2vUYofQ=,tag:MTun8bGoTRSMMzu4IqvsLw==,type:str]
#ENC[AES256_GCM,data:FeShovDFfuKa01d1eAqMi2ks93ZTsw==,iv:Zvez/XfqeIX/aoFg9jbsTrLLZslnaxxMIzP30nL3cs4=,tag:Gw0Gla7dYa5mugPdp/gqjQ==,type:comment]
iran_relay:
    ip: ENC[AES256_GCM,data:k2IwhG7SvbwfAMoFQ5DnvA==,iv:/9m2BnOUSsRg95lNEn69YnqNUTUEDDaaXxMtIo+OGbw=,tag:exTZ3bGJphpa/MgPdAHAvw==,type:str]
    anytls_pass: ENC[AES256_GCM,data:aIxbxJecgQFgp8fgsuxJaVYS5FqSxKZyUg==,iv:Yc8j4uKu939wBsr152T6pNjiGoId2FEt6B4uBj17Vfk=,tag:axgLlZ8TnRGnlv/9aklIRw==,type:str]
    ss_key: ENC[AES256_GCM,data:g2Nrq5O8xxqbGDTi26cGTNpuTIk=,iv:yXnJwLbpjR2MaGqu562p+L7KVxXvOANYdKa7P9qFTpw=,tag:9peA4KO+Zi9sqieNDp7BKg==,type:str]
    exit_cdn_host: ENC[AES256_GCM,data:X5qF9CeYePC+TUaC/yTLe6y80w==,iv:XBsGIFz3lMgj/WBKdGqKEqU4hW6lNjxd06Km7U+otPs=,tag:/XemCePnb/JxcQsJ+anmOw==,type:str]
sops:
    age:
        - recipient: age1xkz6qcj7yywjzqkxd7rs6fcvl0nzdt5uygvrt2f38j7d4umstd6qp6jkk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMjlNWm9vamo5RWxwR0Rv
            azYzREw5eHlxeEhkTDhwN09rK3R4dTV0cXpNCkJvOGZNSUZtckhVOHg5citGbHNV
            VTF5TGRYK0xiM3lpNlNkZ21KVUNBdmsKLS0tIFV4RmJJWHN5YVZpZ1VQWEJySXp6
            RWtvY3ZiSmx4Vy9kWUdwbGFLM21TOVUK0HlwOlIkTb+n/E8KUB22H1ev5qNyKf/k
            zeUStaEdf+e2qQQ9IF/ozZXKyW4P+n7MH1yzN9Q3XqHlKG873vO9Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T01:13:45Z"
    mac: ENC[AES256_GCM,data:D+SKkvgsmxXxz8Wp/mzkpDkfKxtrwQWjXQD3G7vSpcrc8nQx2v1H8HvrTfeQKlNgHwHlWLMUx6t2yMiTtIX6qqOVKSyA/sbGO0XB+DwsnFpVMw59z6OtTnQxdZZ0PUKf6b6t5hUnOYUdxS38m0Nnj/8XB5ofyaSBymTj9uCOcvQ=,iv:2ZA64Sk7VRLuK45yCldAtIK+h/jCstbL6j0CVK/yBUg=,tag:4H8/Y4IP2taq16KmwelWDw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
