---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    domain: example.com
  children:
    vpn_servers:
      hosts:
        helsinki:
          ansible_host: "{{ lookup('env', 'HEL_IP') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/hetzner
          server_tag: hel
          server_location: Finland
          server_provider: Hetzner
        oracle:
          ansible_host: "{{ lookup('env', 'ORC_IP') }}"
          ansible_user: ubuntu
          ansible_become: true
          ansible_ssh_private_key_file: ~/.ssh/oracle
          server_tag: orc
          server_location: Madrid
          server_provider: Oracle
        gcp:
          ansible_host: "{{ lookup('env', 'GCP_IP') }}"
          ansible_user: ubuntu
          ansible_become: true
          ansible_ssh_private_key_file: ~/.ssh/gcp
          server_tag: gcp
          server_location: Dammam
          server_provider: GCP
        scaleway:
          ansible_host: "{{ lookup('env', 'SCW_IP') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/scaleway
          server_tag: scw
          server_location: London
          server_provider: Scaleway
