// ── Probe Script Generator ────────────────────────────────────────
import { CF_CLEAN_IPS } from "./constants";
import type { AppConfig } from "./types";

export function generateProbeScript(
  config: AppConfig,
  reportUrl: string
): string {
  const servers = config.servers.filter(s => s.enabled);
  const cdnDomains = [...new Set(servers
    .map(s => s.cdn_ws?.host)
    .filter((h): h is string => Boolean(h))
  )];

  const serverEntries = servers.map(s => {
    const protocols: string[] = [];
    if (s.reality_pubkey) protocols.push(`reality:${s.reality_port}`);
    if (s.hy2_port) protocols.push(`hy2:${s.hy2_port}`);
    if (s.http_obfs) protocols.push(`http:${s.http_obfs.port}`);
    if (s.finalmask) protocols.push(`xdns:${s.finalmask.xdns_port}:udp`);
    if (s.shadowtls) protocols.push(`stls:${s.shadowtls.port}`);
    if (s.naive) protocols.push(`naive:${s.naive.port}`);
    return `  "${s.tag}|${s.ip}|${protocols.join(',')}"`;
  }).join("\n");

  return `#!/usr/bin/env bash
# ── VPN Iran Probe Script ─────────────────────────────────────────
# Auto-generated by smart-sub worker. Tests VPN reachability from Iran.
# Run: curl -sL <sub-url>/probe | bash
# Or save and run: curl -sL <sub-url>/probe -o probe.sh && chmod +x probe.sh && ./probe.sh
#
# What it tests:
#   1. TCP connectivity to each server (port 443, 80, 8443)
#   2. TLS handshake with Reality SNI domains
#   3. DNS resolution of CDN domains
#   4. HTTPS fetch through CDN (actual connectivity)
#   5. Clean CF IP reachability
#
# Results are POST'd back to the worker, which forwards alerts to Telegram
# server-side. The only credential in this script is a probe-reporting token
# scoped to POST /probe/report — it grants no other access. No VPN configs,
# no admin credential and no bot token are included.

set -euo pipefail

REPORT_URL="${reportUrl}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
RESULTS="[]"

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

log() { echo -e "\$1"; }

add_result() {
  local test_name="\$1" target="\$2" status="\$3" latency="\$4" detail="\$5"
  RESULTS=$(echo "\$RESULTS" | python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
data.append({'test': '\$test_name', 'target': '\$target', 'status': '\$status', 'latency_ms': \$latency, 'detail': '\$detail'})
print(json.dumps(data))
" 2>/dev/null || echo "\$RESULTS")
}

log "\\n\${YELLOW}═══════════════════════════════════════════════════\${NC}"
log "\${YELLOW}  VPN Iran Probe — $(date -u +"%Y-%m-%d %H:%M UTC")\${NC}"
log "\${YELLOW}═══════════════════════════════════════════════════\${NC}\\n"

# ── Detect ISP ──────────────────────────────────────────────────
log "\${YELLOW}[1/5] Detecting ISP...\${NC}"
ISP_INFO=$(curl -s --connect-timeout 5 https://ipinfo.io/json 2>/dev/null || echo '{}')
MY_IP=$(echo "\$ISP_INFO" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('ip','unknown'))" 2>/dev/null || echo "unknown")
MY_ISP=$(echo "\$ISP_INFO" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('org','unknown'))" 2>/dev/null || echo "unknown")
MY_COUNTRY=$(echo "\$ISP_INFO" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('country','??'))" 2>/dev/null || echo "??")
MY_CITY=$(echo "\$ISP_INFO" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('city','unknown'))" 2>/dev/null || echo "unknown")
log "  IP: \$MY_IP  ISP: \$MY_ISP  Country: \$MY_COUNTRY  City: \$MY_CITY"

# ── Test TCP Connectivity ───────────────────────────────────────
log "\\n\${YELLOW}[2/5] Testing TCP connectivity to servers...\${NC}"

SERVERS=(
${serverEntries}
)

for entry in "\${SERVERS[@]}"; do
  IFS='|' read -r TAG IP PROTOCOLS <<< "\$entry"

  # Test port 443 (Reality/HAProxy)
  START=\$(date +%s%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
  if nc -z -w 5 "\$IP" 443 2>/dev/null; then
    END=\$(date +%s%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
    LATENCY=$(( (END - START) / 1000000 )) 2>/dev/null || LATENCY=0
    log "  \${GREEN}✓\${NC} \$TAG (\$IP:443) — \${LATENCY}ms"
    add_result "tcp_443" "\$TAG" "up" "\$LATENCY" "'port 443 reachable'"
  else
    log "  \${RED}✗\${NC} \$TAG (\$IP:443) — BLOCKED"
    add_result "tcp_443" "\$TAG" "down" "0" "'connection refused or timeout'"
  fi

  # Test port 80 (XrayHTTP/SS2022)
  if nc -z -w 5 "\$IP" 80 2>/dev/null; then
    log "  \${GREEN}✓\${NC} \$TAG (\$IP:80)"
    add_result "tcp_80" "\$TAG" "up" "0" "'port 80 reachable'"
  else
    log "  \${RED}✗\${NC} \$TAG (\$IP:80) — BLOCKED"
    add_result "tcp_80" "\$TAG" "down" "0" "'port 80 blocked'"
  fi

  # Test port 8443 UDP (Hysteria2) — best effort
  if command -v nc &>/dev/null && nc -zu -w 3 "\$IP" 8443 2>/dev/null; then
    log "  \${GREEN}✓\${NC} \$TAG (\$IP:8443/udp)"
    add_result "udp_8443" "\$TAG" "up" "0" "'hy2 port reachable'"
  else
    log "  \${YELLOW}?\${NC} \$TAG (\$IP:8443/udp) — unknown (UDP probes unreliable)"
    add_result "udp_8443" "\$TAG" "unknown" "0" "'udp probe unreliable'"
  fi
done

# ── Test TLS Handshake with Reality SNIs ────────────────────────
log "\\n\${YELLOW}[3/5] Testing TLS handshake (Reality SNI)...\${NC}"

REALITY_TESTS=(
  "${servers.map(s => `${s.ip}|${s.reality_port}|${s.sni}|${s.tag}`).join('"\n  "')}"
)

for entry in "\${REALITY_TESTS[@]}"; do
  IFS='|' read -r IP PORT SNI TAG <<< "\$entry"
  START=\$(date +%s%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
  if echo | timeout 5 openssl s_client -connect "\$IP:\$PORT" -servername "\$SNI" -verify_return_error 2>/dev/null | grep -q "Verify return code: 0"; then
    END=\$(date +%s%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
    LATENCY=$(( (END - START) / 1000000 )) 2>/dev/null || LATENCY=0
    log "  \${GREEN}✓\${NC} \$TAG TLS→\$SNI — \${LATENCY}ms"
    add_result "tls_reality" "\$TAG" "up" "\$LATENCY" "'TLS handshake OK with \$SNI'"
  else
    log "  \${RED}✗\${NC} \$TAG TLS→\$SNI — FAILED"
    add_result "tls_reality" "\$TAG" "down" "0" "'TLS handshake failed'"
  fi
done

# ── Test CDN DNS Resolution ─────────────────────────────────────
log "\\n\${YELLOW}[4/5] Testing CDN DNS resolution...\${NC}"

CDN_DOMAINS=(
  ${cdnDomains.map(d => `"${d}"`).join("\n  ")}
  "sub.example.com"
)

for DOMAIN in "\${CDN_DOMAINS[@]}"; do
  RESOLVED=$(dig +short "\$DOMAIN" 2>/dev/null | head -1)
  if [ -n "\$RESOLVED" ]; then
    log "  \${GREEN}✓\${NC} \$DOMAIN → \$RESOLVED"
    add_result "dns_cdn" "\$DOMAIN" "up" "0" "'\$RESOLVED'"
  else
    log "  \${RED}✗\${NC} \$DOMAIN — DNS BLOCKED"
    add_result "dns_cdn" "\$DOMAIN" "down" "0" "'DNS resolution failed'"
  fi
done

# ── Test CDN HTTPS + Clean CF IPs ───────────────────────────────
log "\\n\${YELLOW}[5/5] Testing CDN HTTPS & Clean CF IPs...\${NC}"

CLEAN_IPS=(${CF_CLEAN_IPS.map(ip => `"${ip}"`).join(" ")})

for DOMAIN in "\${CDN_DOMAINS[@]}"; do
  # Direct CDN fetch
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 "https://\$DOMAIN/" 2>/dev/null)
  if [ "\$HTTP_CODE" = "200" ] || [ "\$HTTP_CODE" = "403" ] || [ "\$HTTP_CODE" = "301" ] || [ "\$HTTP_CODE" = "302" ]; then
    log "  \${GREEN}✓\${NC} HTTPS \$DOMAIN → HTTP \$HTTP_CODE"
    add_result "https_cdn" "\$DOMAIN" "up" "0" "'HTTP \$HTTP_CODE'"
  else
    log "  \${RED}✗\${NC} HTTPS \$DOMAIN → HTTP \$HTTP_CODE"
    add_result "https_cdn" "\$DOMAIN" "down" "0" "'HTTP \$HTTP_CODE'"
  fi
done

# Test clean CF IPs (TLS to CDN domain through clean IP)
for IP in "\${CLEAN_IPS[@]}"; do
  CDN_HOST="${cdnDomains[0] || 'cdn.example.com'}"
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 \\
    --resolve "\${CDN_HOST}:443:\${IP}" "https://\${CDN_HOST}/" 2>/dev/null)
  if [ "\$HTTP_CODE" = "200" ] || [ "\$HTTP_CODE" = "403" ] || [ "\$HTTP_CODE" = "301" ]; then
    log "  \${GREEN}✓\${NC} Clean IP \$IP → HTTP \$HTTP_CODE"
    add_result "clean_ip" "\$IP" "up" "0" "'HTTP \$HTTP_CODE via \$CDN_HOST'"
  else
    log "  \${RED}✗\${NC} Clean IP \$IP → HTTP \$HTTP_CODE"
    add_result "clean_ip" "\$IP" "down" "0" "'HTTP \$HTTP_CODE'"
  fi
done

# ── Summary & Report ────────────────────────────────────────────
TOTAL=$(echo "\$RESULTS" | python3 -c "import json,sys; d=json.loads(sys.stdin.read()); print(len(d))" 2>/dev/null || echo "?")
UP=$(echo "\$RESULTS" | python3 -c "import json,sys; d=json.loads(sys.stdin.read()); print(sum(1 for r in d if r['status']=='up'))" 2>/dev/null || echo "?")
DOWN=$(echo "\$RESULTS" | python3 -c "import json,sys; d=json.loads(sys.stdin.read()); print(sum(1 for r in d if r['status']=='down'))" 2>/dev/null || echo "?")

log "\\n\${YELLOW}═══════════════════════════════════════════════════\${NC}"
log "  Total tests: \$TOTAL  |  \${GREEN}Up: \$UP\${NC}  |  \${RED}Down: \$DOWN\${NC}"
log "\${YELLOW}═══════════════════════════════════════════════════\${NC}"

# Build report JSON
REPORT=$(python3 -c "
import json
results = json.loads('''$RESULTS''')
report = {
  'timestamp': '$TIMESTAMP',
  'isp': '$MY_ISP',
  'country': '$MY_COUNTRY',
  'city': '$MY_CITY',
  'ip_prefix': '.'.join('$MY_IP'.split('.')[:2]) + '.x.x',
  'total_tests': len(results),
  'up': sum(1 for r in results if r['status'] == 'up'),
  'down': sum(1 for r in results if r['status'] == 'down'),
  'unknown': sum(1 for r in results if r['status'] == 'unknown'),
  'results': results,
}
print(json.dumps(report))
" 2>/dev/null)

# POST results back to worker
if [ -n "\$REPORT_URL" ] && [ "\$REPORT_URL" != "null" ]; then
  log "\\nSending report to worker..."
  RESP=$(curl -s -X POST "\$REPORT_URL" \\
    -H "Content-Type: application/json" \\
    -d "\$REPORT" 2>/dev/null)
  log "  Response: \$RESP"
fi

# Telegram alerts are sent server-side by /probe/report

log "\\n\${GREEN}Done!\${NC} Results have been reported."
`;
}
